server:
  port: 8081

# used mailtrap for getting mails from. also can use gmail details here.
#https://codecentric.github.io/spring-boot-admin/current/#mail-notifications
spring:
  mail:
    host: smtp.mailtrap.io
    port: #
    username: #
    password: #
    test-connection: true
  boot:
    admin:
      ui:
        brand: "<img src= 'assets/img/spring-boot-logo.png'><span> Online Shopping Service </span>"
        title: 'Application for online shopping portal'
        login-icon: 'assets/img/spring-boot-logo.png'
        available-languages:
          - en
          - fr
        view-settings:
          - name: 'about'
            enabled: false
      notify:
        mail:
          to:
          #our mail id
          ignore-changes:
            - ''