server:
  port: 8080

spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping

  profiles:
    active: local

logging:
  file:
    name: d:\java\microservices\OnlineShoppingPortal\logs\product.log
 #   path: d:\java\microservices\OnlineShoppingPortal\logs #spring.log
  logback:
    rollingpolicy:
      max-file-size: 2MB
  level:
    root: INFO

product:
  currencies:
    - INR
    - USD
    - EUR

---
server:
  port: 8085

spring:
  config:
    activate:
      on-profile:
        - prod




