server:
  port: 8080

spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping

  profiles:
    active: local
  boot:
    admin:
      client:
        url:
          - http://localhost:8081


logging:
  file:
    name: d:\java\microservices\OnlineShoppingPortal\logs\product.log
 #   path: d:\java\microservices\OnlineShoppingPortal\logs #spring.log
  logback:
    rollingpolicy:
      max-file-size: 2MB
  level:
    root: INFO

#actuator specific
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
#  health:
#    mongo:
#      enabled:  false

info:
  app:
    name: Product Microservice
    version: 1.0
    description: Add and Retrieve Product information

product:
  currencies:
    - INR
    - USD
    - EUR

---
server:
  port: 8085

spring:
  config:
    activate:
      on-profile:
        - prod




